### ISSUE TITLE
When a user draw a line it doesn’t show the length label (sometimes). 

### ISSUE THREAD

**Issue by mohammadamin46bd** [getsmap/smap-responsive#214] opened 2016-02-05 09:14 UTC
There is a problem with draw line functionality.
When a user draw a line it doesn’t show the length label for some line segment. It happens sometimes.
It happens  when a uses drwa a line too fast or click the map too fast (tested that problem for those cases).
Attached an image showing the problem.

![drawlinefirstlinetextproblem](https://cloud.githubusercontent.com/assets/14776673/12842155/1fc33a52-cbf1-11e5-8eea-e8be47a5cda2.png)

**Comment by johanlahti** [comment] 2016-02-05 10:16
I am now binding to ”mousedown” instead of ”click” to ensure that the label can finish rendering before the next node is interrupting (cancelling the rendering of previous node’s label).

Could you see if this solves the issue for you too @mohammadamin46bd (after getting the latest code)

**Comment by mohammadamin46bd** [comment] 2016-02-08 07:33
Thanks a lot. 
It solves that problem but seems to be an another problem for that change. 
It also happens when a user draws a line too fast.
Now it can't draw line when a user draws too fast but added the length label there. I have added an image for more description.
![drawlineproblem_hitondraw_problem](https://cloud.githubusercontent.com/assets/14776673/12880217/970ba44c-ce3e-11e5-83b1-6b4d7db6350e.png)

**Comment by johanlahti** [comment] 2016-02-08 09:13
Yes, that was a stupid quick fix I can see now :smile: mousedown will be triggered as soon as the user drags the map, or clicks, since both will trigger mousedown… I will try to find a smarter way. Thanks.

**Comment by johanlahti** [comment] 2016-02-08 11:24
I think the last commit solves it. The problem is that the Leaflet.draw library doesn't trigger any event when a new vertex is added. Therefore, I had to capture this using map "click" or "mousedown". The problem with these two events is that they don't guarantee that a vertex has actually been added. So I had to modify the Leaflet.draw library with an "init-hook" (See below of the MeasureDraw class) so that an event is triggered when a vertex is added (or modified).

Please try again @mohammadamin46bd

**Comment by mohammadamin46bd** [comment] 2016-02-08 15:20
This works great now and thanks a lot. (Excellent!)

**Comment by johanlahti** [comment] 2016-02-08 16:09
Happy to hear that :+1: I'm closing the issue.

**Closed by johanlahti** 2016-02-08 16:09 UTC
Labels: bug
